server:
  port: 8082

# 데이터베이스 연동 설정
spring:
  datasource:
    url: "jdbc:mysql://localhost/member"
    username : "root"
    password : "root1234"
    driver-class-name : com.mysql.cj.jdbc.Driver

  mail:
    username : "yun986927@gmail.com"
    password : "duszcnquhtkstncj"

  # Spring Data JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # 테이블 한번 만들어지고 나서 바뀔때만 변경 (create면 계속 만들어짐)
